name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Deploy only when the main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy files to Hostinger
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 82.112.239.93
          username: u434968181
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd /home/u434968181/domains/goldaana.com/public_html/stage
            git reset --hard
            git pull origin main

